


export const SIGNUP_REQWEST = "SIGNUP_REQWEST";

export const AAD_SHOP = "AAD_SHOP"

export const GET_SHOP = "GET_SHOP"

export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUWEST = "LOGIN_REQUWEST";

export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const FORGET_REQUWEST = "FORGET_REQUWEST";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const LOGOUT_USER ="LOGOUT_USER";
export const LOGGEDREQWEST_USER = "LOGGEDREQWEST_USER"