


export const SIGNUP_REQWEST = "SIGNUP_REQWEST";

export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUWEST = "LOGIN_REQUWEST";

export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const FORGET_REQUWEST = "FORGET_REQUWEST";